# Generated by Django 4.2.7 on 2023-11-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_apartment", models.IntegerField(default=0, unique=True)),
                ("floor", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "square_meter",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status_choice",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Reserved", "Reserved"),
                            ("Purchased", "Purchased"),
                            ("Installment", "Installment"),
                            ("Barter", "Barter"),
                            ("Cancel", "Cancel"),
                        ],
                        default="Active",
                        max_length=11,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("date", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["number_apartment"],
            },
        ),
        migrations.CreateModel(
            name="Object",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Object",
                "verbose_name_plural": "Objects",
                "ordering": ["title"],
                "indexes": [
                    models.Index(fields=["id"], name="apartments__id_4ebec7_idx"),
                    models.Index(fields=["title"], name="apartments__title_1b0673_idx"),
                ],
            },
        ),
    ]
